version: '3.8'
services:
  accountservice:
    build:
      context: ./AccountService
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__AccountServiceDatabase: "Server=sqlserver;Database=AccountDb;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=true"
      ASPNETCORE_URLS: "https://+443"
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      ASPNETCORE_Kestrel__Certificates__Default__Password: WorldOfGamecraft
    ports:
      - "5001:443"
    depends_on:
      - sqlserver

  characterservice:
    build:
      context: ./CharacterService
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__CharacterServiceDatabase: "Server=sqlserver;Database=CharacterDb;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=true"
      ConnectionStrings__Redis: redis:6379
      ASPNETCORE_URLS: "https://+443"
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      ASPNETCORE_Kestrel__Certificates__Default__Password: WorldOfGamecraft
    ports:
      - "5002:443"
    depends_on:
      - sqlserver
      - redis

  sqlserver:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
